[package]
name = "base88"
version = "0.0.1"
edition = "2024"
description = "Fast and safe Base88 encoding/decoding"
license = "MIT"
repository = "https://github.com/rostislavnagimov/base88"
keywords = ["encoding", "base64", "codec", "serialization", "base88"]
categories = ["encoding", "parsing", "algorithms"]
include = ["src/**/*.rs", "Cargo.toml", "README.md", "base88-spec.md"]

[dependencies]

[dev-dependencies]
base64 = "0.22"
